"""empty message

Revision ID: 92d2617456a0
Revises: 
Create Date: 2023-03-28 16:54:33.067170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d2617456a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_ce_param',
    sa.Column('r1', sa.Integer(), nullable=False),
    sa.Column('t2', sa.String(length=20), nullable=False),
    sa.Column('DMi', sa.Integer(), nullable=False),
    sa.Column('H2', sa.String(length=200), nullable=False),
    sa.Column('m2', sa.String(length=200), nullable=False),
    sa.Column('c2', sa.BLOB(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mh_ce_param')
    # ### end Alembic commands ###
